### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by loretoparisi**
I have added a `Dockerfile` that simplifies the build process.

### CODE REVIEW

**Comment by gvne** [comment]
Hello @loretoparisi thank you very much for your work !   
I'd like to use this in the CI script. However, if I am not mistaken, that would force the sources to be copied at runtime. What do you think about just keeping the tensorflow build in your Dockerfile and documenting the build process ?  

- [ ] Update the container for CI use (Copy the sources at runtime ?)
- [ ] Push the container to Docker Hub
- [ ] Add a quick word in the documentation ([How To Build/Docker](https://spleeterpp.readthedocs.io/en/latest/build.html))
- [ ] Update the .travis.yml script

Again, thank you for your help.  
Let me know what you think !

**Comment by loretoparisi** [comment]
@gvne you're welcome! So there are two ways: One is to copying the sources like in this case in the docker container, the other is to use `-v` (the volume ) option with a volume so that the sources are shared with the repo like `-v $(PWD):/spleeterpp/src`, so that you will find it in `/spleeterpp/src` in the docker container. In this case you can run the CD/CI in the repo but running the app in the container.

**Comment by gvne** [comment]
I see. I'll try it this way then. I'll let you know the outcome asap.

**Comment by gvne** [comment]
Hi, I've uploaded the container as `gvincke/spleeterpp-ci:tf-1.14.0` on docker hub and updated the CI script to use it.  
An improvement would be to minimize the size of the image (the 4.39 Go can probably be reduced). But that's not a priority at the moment.  
I also added a short information on the documentation. Feel free to let me know if you want to add something.  

Again, thank you for contributing !

**Pull request merged**
